"""
Словарь EN->RU для медицинской терминологии.
Применяется к техническому отчёту перед подачей в LLM, чтобы:
1) даже если модель срывается на копирование, в ответе уже был русский,
2) модели легче формировать русский ответ - перед глазами уже есть перевод.
"""
import re

# Основные термины. Сначала длинные фразы (чтобы матчиться раньше отдельных слов).
MEDICAL_GLOSSARY_EN_RU = [
    # === Описания применения ===
    ("Treatment of Bacterial infections", "Лечение бактериальных инфекций"),
    ("Treatment of bacterial infections", "Лечение бактериальных инфекций"),
    ("Bacterial infections", "Бактериальные инфекции"),
    ("Prevention of heart attack and stroke", "Профилактика инфаркта и инсульта"),
    ("Prevention of heart attack", "Профилактика инфаркта"),
    ("Prevention of stroke", "Профилактика инсульта"),
    ("Pain relief", "Обезболивание"),
    ("Mild to moderate pain", "Боль лёгкой и умеренной интенсивности"),
    ("Moderate to severe pain", "Боль умеренной и сильной интенсивности"),
    ("Neuropathic pain", "Нейропатическая боль"),
    ("Postoperative pain", "Послеоперационная боль"),
    ("Acute pain", "Острая боль"),
    ("Chronic pain", "Хроническая боль"),
    ("Allergic conditions", "Аллергические состояния"),
    ("Seasonal allergies", "Сезонная аллергия"),
    ("High blood pressure", "Артериальная гипертензия"),
    ("Heart failure", "Сердечная недостаточность"),
    ("Heart attack", "Инфаркт миокарда"),
    ("Cancer of colon and rectum", "Рак толстой и прямой кишки"),
    ("Non-small cell lung cancer", "Немелкоклеточный рак лёгкого"),
    ("Kidney cancer", "Рак почки"),
    ("Brain tumor", "Опухоль мозга"),
    ("Ovarian cancer", "Рак яичников"),
    ("Cervical cancer", "Рак шейки матки"),
    ("Type 2 diabetes mellitus", "Сахарный диабет 2 типа"),
    ("Type 1 diabetes", "Сахарный диабет 1 типа"),
    ("Diabetes mellitus", "Сахарный диабет"),
    ("Acid reflux", "Кислотный рефлюкс"),
    ("Heartburn", "Изжога"),
    ("Peptic ulcer disease", "Язвенная болезнь"),
    ("Stomach ulcer", "Язва желудка"),
    ("Asthma", "Астма"),

    # === Побочные эффекты (Side effects) ===
    ("Increased bleeding tendency", "Повышенная кровоточивость"),
    ("Mucocutaneous candidiasis", "Кожно-слизистый кандидоз"),
    ("Rectal bleeding", "Ректальное кровотечение"),
    ("Taste change", "Изменение вкуса"),
    ("Loss of appetite", "Потеря аппетита"),
    ("Loss of taste", "Потеря вкуса"),
    ("Loss of smell", "Потеря обоняния"),
    ("High blood pressure", "Высокое артериальное давление"),
    ("Low blood pressure", "Низкое артериальное давление"),
    ("Protein in urine", "Белок в моче"),
    ("Blood in urine", "Кровь в моче"),
    ("Blood in stool", "Кровь в кале"),
    ("Inflammation of the nose", "Воспаление слизистой носа"),
    ("Abdominal pain", "Боль в животе"),
    ("Stomach pain", "Боль в желудке"),
    ("Chest pain", "Боль в груди"),
    ("Back pain", "Боль в спине"),
    ("Muscle pain", "Боль в мышцах"),
    ("Joint pain", "Боль в суставах"),
    ("Dry skin", "Сухость кожи"),
    ("Dry mouth", "Сухость во рту"),
    ("Skin rash", "Кожная сыпь"),
    ("Difficulty in breathing", "Затруднённое дыхание"),
    ("Shortness of breath", "Одышка"),
    ("Uncoordinated body movements", "Нарушение координации движений"),
    ("Increased heart rate", "Учащённое сердцебиение"),
    ("Decreased heart rate", "Замедление сердцебиения"),
    ("Liver damage", "Повреждение печени"),
    ("Kidney damage", "Повреждение почек"),
    ("Allergic reaction", "Аллергическая реакция"),
    ("Skin reactions", "Кожные реакции"),

    # Однословные побочки
    ("Nosebleeds", "Носовые кровотечения"),
    ("Headache", "Головная боль"),
    ("Vomiting", "Рвота"),
    ("Nausea", "Тошнота"),
    ("Diarrhea", "Диарея"),
    ("Constipation", "Запор"),
    ("Dizziness", "Головокружение"),
    ("Drowsiness", "Сонливость"),
    ("Sleepiness", "Сонливость"),
    ("Tiredness", "Утомляемость"),
    ("Fatigue", "Усталость"),
    ("Weakness", "Слабость"),
    ("Insomnia", "Бессонница"),
    ("Anxiety", "Тревожность"),
    ("Depression", "Депрессия"),
    ("Fever", "Лихорадка"),
    ("Cough", "Кашель"),
    ("Itching", "Зуд"),
    ("Rash", "Сыпь"),
    ("Bleeding", "Кровотечение"),
    ("Bruising", "Появление синяков"),
    ("Indigestion", "Расстройство пищеварения"),
    ("Heartburn", "Изжога"),
    ("Bloating", "Вздутие живота"),
    ("Sweating", "Потливость"),
    ("Tremor", "Тремор"),
    ("Confusion", "Спутанность сознания"),
    ("Hallucinations", "Галлюцинации"),
    ("Seizures", "Судороги"),
    ("Edema", "Отёки"),
    ("Swelling", "Отёк, припухлость"),
    ("Dehydration", "Обезвоживание"),
    ("Tinnitus", "Шум в ушах"),

    # === Описания взаимодействий ===
    ("may increase the photosensitizing activities of",
     "может усилить фотосенсибилизирующее действие препарата"),
    ("may increase the serum concentration of",
     "может повысить концентрацию в крови препарата"),
    ("may decrease the serum concentration of",
     "может снизить концентрацию в крови препарата"),
    ("can be increased when it is combined with",
     "повышается при совместном применении с"),
    ("can be decreased when it is combined with",
     "снижается при совместном применении с"),
    ("can be increased when used in combination with",
     "повышается при совместном применении с"),
    ("can be decreased when used in combination with",
     "снижается при совместном применении с"),
    ("The therapeutic efficacy of",
     "Терапевтическая эффективность"),
    ("The serum concentration of",
     "Концентрация в крови"),
    ("The metabolism of",
     "Метаболизм"),
    ("The excretion of",
     "Выведение"),
    ("may decrease the excretion rate of",
     "может снизить скорость выведения"),
    ("may increase the excretion rate of",
     "может повысить скорость выведения"),
    ("which could result in a higher serum level",
     "что может привести к повышению уровня в крови"),
    ("which could result in a lower serum level",
     "что может привести к снижению уровня в крови"),
    ("The risk or severity of adverse effects can be increased",
     "Риск или тяжесть побочных эффектов могут возрастать"),
    ("The risk or severity of bleeding can be increased",
     "Риск или тяжесть кровотечений могут возрастать"),
    ("when combined with",
     "при сочетании с"),
    ("when used in combination with",
     "при сочетании с"),

    # Глагольные формы
    ("may increase",  "может повышать"),
    ("may decrease",  "может снижать"),
    ("may cause",     "может вызывать"),
    ("can lead to",   "может привести к"),
    ("can result in", "может привести к"),

    # Названия групп лекарств
    ("antibiotic", "антибиотик"),
    ("antibiotics", "антибиотики"),
    ("antiviral", "противовирусный препарат"),
    ("antifungal", "противогрибковый препарат"),
    ("antihistamine", "антигистаминный препарат"),
    ("anticoagulant", "антикоагулянт"),
    ("antidepressant", "антидепрессант"),
    ("painkiller", "обезболивающее"),
    ("analgesic", "анальгетик"),
    ("anti-inflammatory", "противовоспалительный"),
    ("vasodilator", "сосудорасширяющий препарат"),

    # --- Расширение: частые фразы взаимодействий ---
    ("the risk or severity of", "риск или тяжесть"),
    ("can be increased", "могут возрастать"),
    ("can be decreased", "могут снижаться"),
    ("the absorption of", "всасывание"),
    ("the protein binding of", "связывание с белками"),
    ("serum concentration", "концентрация в крови"),
    ("therapeutic efficacy", "терапевтическая эффективность"),
    ("metabolism", "метаболизм"),
    ("excretion", "выведение"),
    ("absorption", "всасывание"),
    ("bioavailability", "биодоступность"),
    ("can be combined with", "при сочетании с"),
    ("is combined with", "сочетается с"),
    ("when it is combined with", "при сочетании с"),

    # --- Расширение: частые побочные эффекты (одно слово) ---
    ("increased liver enzymes", "повышение печёночных ферментов"),
    ("increased", "повышенный"),
    ("decreased", "сниженный"),
    ("liver enzymes", "печёночные ферменты"),
    ("hair loss", "выпадение волос"),
    ("weight loss", "снижение веса"),
    ("weight gain", "набор веса"),
    ("dyspepsia", "диспепсия"),
    ("flatulence", "метеоризм"),
    ("deafness", "снижение слуха"),
    ("blurred vision", "нечёткость зрения"),
    ("vision", "зрение"),
    ("ringing in ear", "звон в ушах"),
    ("ringing in the ears", "звон в ушах"),
    ("vertigo", "вертиго (головокружение)"),
    ("flushing", "приливы"),
    ("sense of warmth", "ощущение жара"),
    ("dry mouth", "сухость во рту"),
    ("dryness", "сухость"),
    ("dry eye", "сухость глаз"),
    ("dry skin", "сухость кожи"),
    ("skin", "кожа"),
    ("eye", "глаза"),
    ("mouth", "рот"),
    ("throat", "горло"),
    ("nasal", "носовой"),
    ("inflammation", "воспаление"),
    ("irritation", "раздражение"),
    ("application site", "место нанесения"),
    ("injection site", "место инъекции"),
    ("burning", "жжение"),
    ("redness", "покраснение"),
    ("difficulty sleeping", "нарушение сна"),
    ("difficulty", "затруднение"),
    ("muscle pain", "мышечная боль"),
    ("muscle", "мышцы"),
    ("tremors", "тремор"),
    ("tremor", "тремор"),
    ("blood glucose", "уровень глюкозы в крови"),
    ("blood pressure", "артериальное давление"),
    ("blood level", "уровень в крови"),
    ("blood", "кровь"),
    ("glucose", "глюкоза"),
    ("pressure", "давление"),
    ("level", "уровень"),
    ("low", "низкий"),
    ("high", "высокий"),
    ("respiratory tract", "дыхательные пути"),
    ("urinary tract", "мочевыводящие пути"),
    ("tract infection", "инфекция путей"),
    ("tract", "тракт"),
    ("infection", "инфекция"),
    ("reactions", "реакции"),
    ("reaction", "реакция"),
    ("rheumatoid arthritis", "ревматоидный артрит"),
    ("psoriatic arthritis", "псориатический артрит"),
    ("arthritis", "артрит"),
    ("malaria", "малярия"),
    ("bronchitis", "бронхит"),
    ("inflammation of the airways", "воспаление дыхательных путей"),
    ("airways", "дыхательные пути"),
    ("sleeping", "сон"),
    ("drop", "снижение"),
    ("gain", "набор"),
    ("face", "лицо"),
    ("neck", "шея"),
    ("ears", "уши"),
    ("ear", "ухо"),
    ("trunk", "туловище"),
    ("sweating", "потливость"),
    ("warmth", "тепло"),
    ("sense", "ощущение"),

    # --- Финальное расширение ---
    ("treatment of", "лечение"),
    ("treatment", "лечение"),
    ("pain relief", "обезболивание"),
    ("pain", "боль"),
    ("abnormal", "нарушение"),
    ("hypotension", "пониженное давление (гипотензия)"),
    ("hypertension", "повышенное давление (гипертензия)"),
    ("hypoglycemia", "гипогликемия (низкий сахар)"),
    ("hyperglycemia", "гипергликемия (высокий сахар)"),
    ("orthostatic hypotension", "ортостатическая гипотензия"),
    ("palpitations", "учащённое сердцебиение"),
    ("sensation", "ощущение"),
    ("stomach pain", "боль в желудке"),
    ("stomach", "желудок"),
    ("upper respiratory", "верхних дыхательных путей"),
    ("upper", "верхний"),
    ("heart rate", "частота сердечных сокращений"),
    ("heart", "сердце"),
    ("sudden", "внезапный"),
    ("lowering", "снижение"),
    ("standing", "при вставании"),
    ("cells", "клетки"),
    ("white blood cells", "лейкоциты"),
    ("red blood cells", "эритроциты"),
    ("platelets", "тромбоциты"),
    ("kidney", "почки"),
    ("renal", "почечный"),
    ("hepatic", "печёночный"),
    ("cardiac", "сердечный"),
    ("gastrointestinal", "желудочно-кишечный"),
    ("constipation", "запор"),
    ("flushing sense of warmth", "приливы жара"),
    ("loss of", "потеря"),
    ("loss", "потеря"),
    ("numbness", "онемение"),
    ("tingling", "покалывание"),
    ("blurred", "нечёткий"),
    ("restlessness", "беспокойство"),
    ("agitation", "возбуждение"),
    ("drowsiness", "сонливость"),

    # --- Термины, замеченные в выводе модели (доработка) ---
    ("nasopharyngitis", "назофарингит"),
    ("pharyngitis", "фарингит"),
    ("rhinitis", "ринит"),
    ("urinary tract infection", "инфекция мочевыводящих путей"),
    ("urinary tract", "мочевыводящие пути"),
    ("urinary", "мочевыводящий"),
    ("liver function tests", "показатели функции печени"),
    ("liver function test", "показатель функции печени"),
    ("liver function", "функция печени"),
    ("renal function", "функция почек"),
    ("kidney function", "функция почек"),
    ("function tests", "показатели функции"),
    ("upper respiratory tract infection", "инфекция верхних дыхательных путей"),
    ("respiratory tract infection", "инфекция дыхательных путей"),
    ("inflammation of the throat and nasal passages",
     "воспаление горла и носовых ходов"),
    ("nasal passages", "носовые ходы"),
    ("passages", "ходы"),
    ("throat", "горло"),
    ("in extremities", "в конечностях"),
    ("extremities", "конечности"),
    ("peripheral edema", "периферические отёки"),
    ("peripheral", "периферический"),
    ("hypersensitivity", "гиперчувствительность"),
    ("anaphylaxis", "анафилаксия"),
    ("urticaria", "крапивница"),
    ("myalgia", "миалгия (боль в мышцах)"),
    ("arthralgia", "артралгия (боль в суставах)"),
    ("paresthesia", "парестезия (покалывание)"),
    ("malaise", "недомогание"),
    ("asthenia", "астения (слабость)"),
    ("pyrexia", "лихорадка"),
    ("epistaxis", "носовое кровотечение"),
    ("dyspnea", "одышка"),
    ("dyspnoea", "одышка"),
    ("tachycardia", "тахикардия"),
    ("bradycardia", "брадикардия"),
    ("hypotension", "пониженное давление"),
    ("somnolence", "сонливость"),
    ("lethargy", "вялость"),
]


def translate_medical_terms(text: str) -> str:
    """
    Заменяет английские медицинские термины на русские.
    Применяется к техническому отчёту перед подачей в LLM.
    Сортируем по длине (длинные сначала), чтобы 'Loss of appetite' матчилось раньше 'Loss'.
    """
    if not text:
        return text
    out = text
    sorted_pairs = sorted(MEDICAL_GLOSSARY_EN_RU, key=lambda p: -len(p[0]))
    for en, ru in sorted_pairs:
        # \b не работает с не-ASCII, поэтому используем lookahead/lookbehind
        # на не-буквенный символ. Используем re.IGNORECASE.
        pattern = re.compile(
            r'(?<![A-Za-z])' + re.escape(en) + r'(?![A-Za-z])',
            flags=re.IGNORECASE,
        )
        out = pattern.sub(ru, out)
    return out
